spring:
  datasource:
    url: jdbc:mysql://localhost:3312/login_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: user1
    password: pass1
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false

access-token:
  duration_minutes: 30
